"""add min_age and max_age to activities

Revision ID: 40d34bbe781d
Revises: aab4e722f40b
Create Date: 2026-09-12 11:14:30.874068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d34bbe781d'
down_revision = 'aab4e722f40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_age', sa.Integer(), server_default='4', nullable=False))
        batch_op.add_column(sa.Column('max_age', sa.Integer(), server_default='14', nullable=False))
        batch_op.create_index(batch_op.f('ix_activities_max_age'), ['max_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_min_age'), ['min_age'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_min_age'))
        batch_op.drop_index(batch_op.f('ix_activities_max_age'))
        batch_op.drop_column('max_age')
        batch_op.drop_column('min_age')

    # ### end Alembic commands ###
