"""Add activity_sessions and interaction_events tables

Revision ID: 639037f2c865
Revises: 114000817c02
Create Date: 2026-09-11 00:34:13.140642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639037f2c865'
down_revision = '114000817c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name='ck_session_status_valid'),
    sa.CheckConstraint('accuracy >= 0.0 AND accuracy <= 100.0', name='ck_session_accuracy_range'),
    sa.CheckConstraint('attempts >= correct_answers', name='ck_session_attempts_gte_correct'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_session_duration_non_negative'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_sessions_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sessions_child_id'), ['child_id'], unique=False)

    op.create_table('interaction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['activity_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['activity_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interaction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_events_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_question_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_child_id'))

    op.drop_table('interaction_events')
    with op.batch_alter_table('activity_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_sessions_child_id'))
        batch_op.drop_index(batch_op.f('ix_activity_sessions_activity_id'))

    op.drop_table('activity_sessions')
    # ### end Alembic commands ###
