"""add priority_score and persistence_count to content_suggestions

Revision ID: 7d7fab82e627
Revises: a6aed6bcb9ae
Create Date: 2026-09-13 16:31:38.509305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7fab82e627'
down_revision = 'a6aed6bcb9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_score', sa.Float(), nullable=False, server_default=sa.text('0.0')))
        batch_op.add_column(sa.Column('persistence_count', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.create_index(batch_op.f('ix_content_suggestions_priority_score'), ['priority_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_suggestions_priority_score'))
        batch_op.drop_column('persistence_count')
        batch_op.drop_column('priority_score')

    # ### end Alembic commands ###
