"""Add progress_records table

Revision ID: 8a5e6f4c1c8d
Revises: 639037f2c865
Create Date: 2026-09-11 00:43:51.148500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5e6f4c1c8d'
down_revision = '639037f2c865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('accuracy >= 0.0 AND accuracy <= 100.0', name='ck_progress_accuracy_range'),
    sa.CheckConstraint('engagement_score >= 0.0 AND engagement_score <= 100.0', name='ck_progress_engagement_range'),
    sa.CheckConstraint('performance_score >= 0.0 AND performance_score <= 100.0', name='ck_progress_performance_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_records_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_progress_records_child_id'))
        batch_op.drop_index(batch_op.f('ix_progress_records_category_id'))

    op.drop_table('progress_records')
    # ### end Alembic commands ###
