"""add content_suggestions table

Revision ID: a6aed6bcb9ae
Revises: aed41a63fe0c
Create Date: 2026-09-12 22:44:12.651951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aed6bcb9ae'
down_revision = 'aed41a63fe0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('age_band', sa.String(length=20), nullable=True),
    sa.Column('target_difficulty', sa.String(length=20), nullable=True),
    sa.Column('suggested_title', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_suggestions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_suggestions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_suggestions_suggestion_type'), ['suggestion_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_suggestions_suggestion_type'))
        batch_op.drop_index(batch_op.f('ix_content_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_content_suggestions_created_at'))
        batch_op.drop_index(batch_op.f('ix_content_suggestions_category_id'))

    op.drop_table('content_suggestions')
    # ### end Alembic commands ###
