"""add health_snapshots table

Revision ID: aed41a63fe0c
Revises: 5e91a0b3c4f2
Create Date: 2026-09-12 16:12:43.927987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed41a63fe0c'
down_revision = '5e91a0b3c4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('valid_activities_pct', sa.Float(), nullable=False),
    sa.Column('children_with_rec_pct', sa.Float(), nullable=False),
    sa.Column('compliance_incidents_count', sa.Integer(), nullable=False),
    sa.Column('integrity_issues_count', sa.Integer(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_snapshots_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_snapshots_created_at'))

    op.drop_table('health_snapshots')
    # ### end Alembic commands ###
