"""Add recommendations table

Revision ID: b3ef6abebb43
Revises: 8a5e6f4c1c8d
Create Date: 2026-09-11 00:55:21.922600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ef6abebb43'
down_revision = '8a5e6f4c1c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))
        batch_op.drop_index(batch_op.f('ix_recommendations_child_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_activity_id'))

    op.drop_table('recommendations')
    # ### end Alembic commands ###
