from datetime import datetime, timezone
from app import db


class ContentSuggestion(db.Model):
    """
    Stores adaptive content suggestions generated by ContentSuggestionAgent.
    Suggestions highlight content gaps, progression bottlenecks, or age band imbalances.
    Never auto-publishes; requires human administrator review.
    """
    __tablename__ = 'content_suggestions'

    STATUS_PENDING = 'pending'
    STATUS_APPROVED = 'approved'
    STATUS_DISMISSED = 'dismissed'
    STATUSES = [STATUS_PENDING, STATUS_APPROVED, STATUS_DISMISSED]

    TYPE_PROGRESSION_GAP = 'progression_gap'
    TYPE_AGE_COVERAGE_GAP = 'age_coverage_gap'
    TYPE_CONTENT_IMBALANCE = 'content_imbalance'
    TYPE_NEW_CATEGORY = 'new_category'

    id = db.Column(db.Integer, primary_key=True)
    suggestion_type = db.Column(db.String(50), nullable=False, index=True)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id', ondelete='SET NULL'), nullable=True, index=True)
    age_band = db.Column(db.String(20), nullable=True)
    target_difficulty = db.Column(db.String(20), nullable=True)
    suggested_title = db.Column(db.String(150), nullable=True)
    reason = db.Column(db.Text, nullable=False)
    priority_score = db.Column(db.Float, nullable=False, default=0.0, index=True)
    persistence_count = db.Column(db.Integer, nullable=False, default=1)
    status = db.Column(db.String(20), nullable=False, default=STATUS_PENDING, index=True)
    created_at = db.Column(
        db.DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True
    )

    category = db.relationship('Category', backref=db.backref('suggestions', lazy='dynamic'))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @property
    def is_pending(self):
        return self.status == self.STATUS_PENDING

    @property
    def is_approved(self):
        return self.status == self.STATUS_APPROVED

    @property
    def is_dismissed(self):
        return self.status == self.STATUS_DISMISSED

    def to_dict(self):
        return {
            'id': self.id,
            'suggestion_type': self.suggestion_type,
            'category_id': self.category_id,
            'category_name': self.category.name if self.category else None,
            'age_band': self.age_band,
            'target_difficulty': self.target_difficulty,
            'suggested_title': self.suggested_title,
            'reason': self.reason,
            'priority_score': self.priority_score,
            'persistence_count': self.persistence_count,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

    def __repr__(self):
        return f"<ContentSuggestion id={self.id} type={self.suggestion_type} status={self.status}>"
